services:
  - type: web
    name: medalpaca-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    branch: main
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO
